# Generated by Django 4.2.29 on 2026-03-29 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(verbose_name='История автора')),
                ('philosophy', models.TextField(verbose_name='Философия')),
            ],
            options={
                'verbose_name_plural': 'Об авторе',
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='Изображение')),
                ('caption', models.CharField(max_length=255, verbose_name='Подпись')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Галерея',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Thought',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Тема размышления')),
                ('content', models.TextField(verbose_name='Мысль')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата записи')),
                ('mood', models.CharField(blank=True, max_length=50, verbose_name='Настроение')),
            ],
            options={
                'verbose_name': 'Запись в дневник',
                'verbose_name_plural': 'Записи дневника',
                'ordering': ['-created_at'],
            },
        ),
    ]
