upstream backend {
    server backend:8000;
}

server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        proxy_pass http://backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
    
    location /admin/ {
        proxy_pass http://backend;
        proxy_set_header Host $host;
    }

    location /static/ {
        proxy_pass http://backend;
    }

    location /media/ {
        alias /vol/media/;
        
        expires 30d;
        add_header Pragma public;
        add_header Cache-Control "public";
    }
}